.PCsCADProject 'C:\Users\m.karabela\Desktop\pcs_diff\test cases\case3.PRO' V18.0 6 257 1244807787 '18-01-2017 08:19:18' 2 2500 500 2500 500 2500 Standard 1 "" "" 27 0
.Title 'test project' 0
.Born 2 0 18.0 1244807439

.xyz 0

.AppData [LineGap]
.AppData LineGapStatus=0
.AppData [IEC/EN_61175_PreTexts]
.AppData SignalRefPreText=/
.AppData SymbolRefPreText=/
.AppData CrossRefPreText=/

.Revision 0 0

.LayTab 0 'Warstwa 0' 1
.LayTab 1 'Warstwa 1' 129


.DefText .TextVis¤¤¤¤ 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .FieldVis¤¤¤¤ 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .NAMEVis¤¤¤¤ 1250 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .TypInv¤¤¤¤ 1250 2500 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .ArtInv¤¤¤¤ 1250 -4000 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .FuncVis¤¤¤¤ 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .PINNAMEVis¤¤¤¤ 0 1000 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .PinFuncVis¤¤¤¤ 0 -2750 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText .PinLabInv¤¤¤¤ 0 0 0 0 0 25 0 0 0 0 0 2 0 0 0 0 0
.DefText .PinDesVis¤¤¤¤ 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText '.SignalRefVis¤¤12  %s.%s¤¤' 0 -3000 0 0 16711680 18 0 0 0 2 0 0 0 0 0 0 0
.DefText '.SingleRefVis¤¤12  %s.%s$$2   %s¤¤' 0 -3000 0 0 16711680 18 0 0 0 2 0 0 0 0 0 0 0
.DefText '.MultiRefVis¤¤12  %s.%s$$2   %s¤¤' 0 -3000 0 0 16711680 18 0 0 0 2 0 0 0 0 0 0 0
.DefText '.XRefVis¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 32768 25 0 4 0 0 0 2 0 0 0 0 0
.DefText '.YRefVis¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 32768 25 0 4 0 0 0 2 0 0 0 0 0
.DefText '.LnameVis¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText '.LtypInv¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 16711680 18 0 0 0 0 0 0 0 0 0 0 0
.DefText '.LartInv¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0
.DefText '.LfuncInv¤¤12  %s.%s$$2   %s¤¤' 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0

.WireNoSetup 0 WIRENO 0 0 0 2 / 0 ""
.ContactRefSetup 0 6 12 3 10000 1000

.RefDispFormat FLN|FLN

.ProText 'Numer projektu' "" -1
.ProText 'Numer rewizji' "" -1
.ProText 'Nazwa klienta' "" -1
.ProText Adres "" -1
.ProText 'Kod pocztowy' "" -1
.ProText Miasto "" -1
.ProText Telefon "" -1
.ProText Fax "" -1
.ProText Temat "" -1
.ProText 'Nr rysunku' "" -1
.ProText Projektant "" -1
.ProText Zatwierdził "" -1
.ProText 'Data zatwierdzenia' "" -1
.ProText Sprawdził "" -1
.ProText 'Nazwa firmy' "" -1
.ProText 'Kod i nazwa firmy' "" -1
.ProText 'Adres firmy' "" -1
.ProText 'Telefon firmy' "" -1
.ProText 'E-mail firmy' "" -1
.ProText 'PRewizja 01' "" -1
.ProText 'PRewizja 02' "" -1
.ProText 'PRewizja 03' "" -1
.ProText 'PRewizja 03' "" -1

.PageText 'Nr rysunku' "" -1
.PageText Zatwierdził "" -1
.PageText Data "" -1
.PageText Sprawdził "" -1
.PageText Projektant "" -1
.PageText 'SRewizja 01' "" -1
.PageText 'SRewizja 02' "" -1
.PageText 'SRewizja 03' "" -1
.PageText 'SRewizja 04' "" -1


.Picture 'Y:\PROJEKTY\PCSCHEMATIC\FORMATKI\LOGO\LOGO PREVAC.JPG' 129 -7212 5288 0 15800 17556 0


.PageNo 1 1 '18-01-2017 08:13:26' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807472




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.PageNo 2 2 '18-01-2017 08:13:24' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807588




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.PageNo 3 3 '18-01-2017 08:13:28' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807594




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.PageNo 4 4 '18-01-2017 08:13:30' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807593




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.PageNo 5 5 '18-01-2017 08:13:30' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807592




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.PageNo 6 6 '18-01-2017 08:19:16' 4 10000 1 0 300 1 0 16 0 0 0 210000 148500 0 A3|ISOA 420000 297000 -25000 -10000 -10000 -10000 0 -1
.Title 'Page title' 0
.Born 2 0 18.0 1244807782




.Refdata 1 1 45000 269500 10000 47500 7 0 1 A 30000 40000 12 6 60000 30000


.Text 'Project content' 197500 162500 0 1 0 25 0 4 0 0 0 0 0 0 0 0 0
.Field 'Data ostatniej zmiany' 195000 105000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Last modified: ' 24 0 ' ' 3 "" ""
.Field 'Numer strony' 197500 130000 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page number: ' 22 0 ' ' 3 "" ""
.Field 'Nazwa strony' 197500 122500 0 1 0 25 0 1 0 0 0 0 0 0 0 0 0
.Fdata 'Page name/title: ' 23 0 ' ' 3 "" ""

.end

.Objects V18.0
.ExtObj ""
.ExtObjData IMG0
AD773B163226DE87BBF8CBA4A8E35206
eJzFeGdU08277S/SpYO8KIL0Ij1IkS4oYOgQQpXewdB7B6WIFAnSBYHQqxAJvShNiiAdCQGRHgzS
e7m8Z93/uvfbvefT2WvNrJnZz7P3zIcpawivZ69/ATTqqhBVAHQDQZAgAFxfATyqzi/t2fy9nH18
7N3YbALZlOzcbezZdJ3cfdy9ndw9FNnEhUWvMcBTgODWv/i3JrgBITHhvyAlJiYiJiO9fZuMlIzs
NgU1xW1yKnIyMkpaSipqGhpamtsUdPR0NPQ3bZp/RUD/ZhIQkt4k0pCTkdP8t3HdBdCSAi+BAAIQ
LXCLFkRAC7ruAVgAgAAE+q/yH5CQkhGDCIgIb93Q6jTArRvnWzddIhISyhsWdIuAkIgYIKElpSOj
Z7/DAVbSYzRKG2e4J2ad8g+nvmfk+zEuZRvb1IIJ3kfSUEN7b39EHaph50br/o3Hrf/b6L/EiIhJ
CG9IqZs5gW4R3iIlukVMAPoPSUtIxA6mUyLWs/aMTCkYoxer+7JzZ+mfR8r6Nl4cXNzQ6zmA4ib6
Fi0BLaAIjArZKET8II441v0xPb9lhcbwrVdWVqRYR+WRzkG4U5Jvx1WQOXBFAMyp+YIsGTuNOEav
zYK2tbVYd7h+xGCj7vg8F3SHI03RdukLXdtL6Qebk2Vove8co5i/t90yweJJL9GCb8UrAMZLTi8X
l7Dd/eebIWiCS0b/yxXcPF9lzgM/4dQz+36O59XBRBFRsWnpwUQSzxbx9qrhGTNQO6M3ueQvw4bE
w6BwYjro0pznmbZibEbxu1bpF2+R2+l7mabkNV+sNhdHfd5LBjjZu4XVQ197X4QqmHoU9PQQr5yo
H+y/VxNSXbSoF+T4dA185zAIS0Hq1Pp4f5TurPe8bEm6o57DUb2zM4uTcnSuqE1/ay7pa1Wy7Vf5
KTaobJlwZ3xcdB+0PHka5lJ2KNTFC/N0asm2Kxn81suiXo8gVaRRG9J9IQ7KpwScCJ5IynhsIr2C
cr8ncUfq9VMK0VXNuPbqWqvBo5vxYqKEqGZDsrvHH2IU4mtw6ivSxj+Fc2Skfo5k/Tnov1vf6zuo
yS5Q73ICq+T1Ig0XyFMRV2tKFlaQ1m3Hc1Ltp3AlCGslwyH/24kJ+EEvYpBLiCfR151coYX2v1mn
ulN8FfVBtIxz1QjgR+1Rs1xUvWogCXc5YmoqMYEgWY5RtlKcpcMLSIL5Vt46QzUst5Cm1pr+zMQx
TcOdPQ/ZZTfpQ1DGL1zV7XgJ+HD5/C8frpt1MV2K+6xnHco2f8YEv/lOSUGrgm8MLn6yHb/4rKpi
78iLokaDv8gqargbEccymfaTzk9Kx9HP/9bsh9uv3I7WRt5LtrAvciWA8tD5ZdRQ3V/UYkZ45kYA
YDDgrygbTEsQmsd/ZtvRYRUCCf8ViYv5Cg9JNfWcO0VVDjtdPLXzceF6xy8mmGZ3xOB2Dcy91jRA
EgMR1BoRG2jZe86TllSKq51RiyPYmNh744I8DDtfdodQ7oquCItfAfnuaDX8nSb5DNaeh0Vu1lls
ElMptXI7Fu5rZhMR4VmsYo9Pfe9axFqVm0yn5uxZZJ992OYsvtuSra8u8P1sc0NwW97X19pnec4/
plk2lARltlF+DZwsWfjWx6ruNcFVAtBXVSf2eWt0C8g9jY1kOLVFqKnZ0h4bFhdrmfxorozH/VL/
ic75Id3GNEzKX2NaY2MgKTxTzSXv7aznLwX+nFyXNLb50M5PK3cqmfrXzYoQi/qWH02Y69IlD9ax
Bkqjw6568RsWTC4ngU0dWKOfZyj72E1YwKbpbQ2U2rFFHAr9tEooabEcMfPGTt+stsYMPRCgUlL9
jmp52OqRmlRLcVPibDTzJ3Ove0kqiUOMDMYLivMNFnIz8eaxOpEjok2XDwfHcUGKi11+Ib6lklHr
4ZKcRDhWt5r7oR/MCtIcExewL2yFJNCounSZzCZ7+W863IGgfv75ck7dqQHtPmp31WFHDEmTEUvj
vBkE2aybd+KgbJrXkvWGdnKik6CDFy/3AEQoJmpkCOubShjAMiu8/jippyFXTkgrh3j+hZYW4mC7
ARBMppYRb/tAJrRYtWRFnto26UJrLEMNmlYa+MteTKZsQwPjdXw8BO4wg/X7jCzkuqvKTe5ybQ+S
6yvtoii6mbrAOUn2mQsP8YaumjyFNTV+S7Z6N6JTmQgGmJKDA0wXAqwWKJfwFCJVLHTsT08SYJVP
qbWmKvAMzalY3cMvTfJKMxrR1p7TyycGqEybxif9GOF5RDle8yPN/NmTolIhnB1/lfxTng08RY0i
U0MxtBaxfRx07BJ45Zg7PWz5tfgauOvrHXqF8c/LrdrZwQl4Pcxvwb48MIaj3froLIudcBaPdgU0
48cFqDcGOddTLm1mF96vnqh1E69dA/3u8m01qozIpnnl34gl89ZT93Wbt31tvKK4ALNT69bj7FPS
YxU0loGj9vA0UcT/vGF0erPB8SIb4o++SpcSP+OFhIshQwdEvLcnA6AvkcpfMzxQcWucWGcepC/J
1hybvtr2urGRFjhj+gN8edshlOErBjI0Mau33nHnPNqlJKi9Zb5V8sngSB9i9fnRpuxj+Yqkan7Z
C5L21drRlJ3pCcoJdXq/HqgnXvtq0ds8bqPYuPJHduhZMEJ4Gc+zCmf4ZdzIS9k067KYyvg5H6xJ
wpxZrGz7nkqN+16EQjZuJ/OPggxzQGC5SGkQNuDDAi+JJYnw7THnq5cjz71I+QM4J1lCHYfNL9lP
Ysw9cZl++2Wy32HjM3Lx6RcIv79lhbyRPw37p407bKBDBStSQSmru/fWVZCwMCRQLey5ct7y0WG0
7u+MPQt7mmTZMsvMQ2/zS9dGX8yQunU2f5x+ABeEI+UpsmDVRKeM7aKvbbckNwtTkleW3qYsY6Fd
4OfnOiKldH9t1kXDs0Gs77uQHSgwL84vCvKOz6mf5LRHZfVp3RRXjanwcI+73obvU7BxgOOf4eDq
yYaWS18kvcknPiolXWYp2ykBQqS22pfXwzzAGa121/7OIwY/Q7dvGBY70Tyy5ScOlnqBfcuH/e1b
dRjBREmWBJiYlslaiorgoLqGpWytwKoIxafI+WHZrEAxv1qkvXGIopqHZXVfuJiGW2iKeXtYK7OC
rQU6MP5SmHElWcH8L6ryWFA4V0Z5biS3ehPqiDSb1hNUT/M/m4390J8Mi5TmyBMLPDZIV4jMOldj
znPNs/E2MXWPYS7suHTf5fIJ9NOLHUIGVI6ef8RU7uv1h3XO7poJOaggsBvVhq0+QnpGZiYy3YS0
tb3Y2Yj8UMj0+7l3JfiTVri2BJS70Un0bZ7L1uaZcr1hw1ieGpKjDf5od5+SOZz66f7UiwwOHHVm
ck4fY8jcp7b7jlHcIv5F2mmJbKzau4+Zr64W/0x6is2TeuBF3m4vWuCs0e482HlPrxX2FlOHS3b1
0rU9ZZhDYrgXWc6xU/E0rLvsc/hKbBm2iSLZ9vvO1m+v2vtVO88NUja6p6X1IlnXWkQV67sttVnp
jcj1YAW894SdTrd+lMa9KjWU0hxWqA8SaPW5NP7ZQedS00RpV0BR/25izsH7azeYtfE+67OMSJyy
VPvceJCf0jjpmuuv6fGKPddqv8NahpKF8A8r9UOLvcXVUpuzV6NfjoZkNpNCxhQp88oEBFYsclE5
qSO7yhM2DXRR31f7iosLhQ4MoFwhySomjHmErjUExc1isVfRRFcLsoqondCXeBmpbOnwiaprYAaz
3RZMSXKS6BFrYx0bxzPwtN5cw3KjWlw5u/c9KGUuhQHGqR7jLsN9+1ZF0ZaoAeBXmnH+pm8qK1t4
o/mC4+hILthapPWVhLRpW8fZBuKiCIlUYg4JNxg1ugaWKp8VLRRPVN6hzbXb5j4m/OlSaXgXpWCW
MwP97Ue6xPZ8yvd1OX9vrC3p6/bqUWTm6cH0FvvXbvoEaPWekvRQc9hRp/13Q8+4XAqBRJE8uIp/
J2a6H7NZWjrvWqrVgOyuJmNRmc4Xgm2vkAiZGRv40zwnfNaJYjrzQKYOPUJZf9+Xyaphn/o4+Dke
Z/H3Y0NCs5slRUtUKctpRyN+8pGIVI62rFPNN5EZftfQ+p9aQvZwc83Cx86/EjUGOJsPYDBCRChA
uGX4kkJi61GVYGOF5sJz9rxCbIQJ//ys4Jc4Os/5KHRR+EfdDR1gj90IXMo1wNWEac4G18ngyIkj
xAk6i6kqUG4Zjzb+ot+U1vbVUKVYCiZyBsJ0j0V8Umo9YGUwS6+nOyvlq8aJ9HUmqmvLmK1PWlsY
l+BEvtJOG5O0cnslwZflMDU9VjkxUarXlR4GEYOBhMQPPqrwo5AShjko05KQqYd9VebSlaVIcGmF
UGyzz36rvyCPjqSr3DWwOi3TTM0TxOjwhyIAaKEZ68w/Tn0HWNfaDqD41jKNpy0lx811fm4ni3z3
oBvapcoQmvFfi5pg+eb+OEkJPlg3uFbYMsf/u6awHGYI1qGPVV2KhHaDNpRIfikxzU4V3z5YVS9s
M0VtO3arF5V9N3iFMkX6o3M84bIo9OzasommTfY1oMRg8oZ7n0iux1OcqIn5sxdJwhm1gcyuoNs/
AczPdvYXhLGXOr0uQSP0tMzmpNNJ40bHFtTK4N0wzPt2OBVv8+cf/jBbxpL83AiCePVvl8Yf3/w2
ZgPCq+Ah+mozJOUqPkqJ/fEHGQ3Ts6kNLp4nbh8896uEDHR2P+DGZqsaH8ggiOT/MiU/wil88Wga
T4U03v3TKCMW3IXo2BR8j1uOYmgrc3IhIXxAqd5YAGw5aqMKMkbAQZNpH33owmo0vs2MZPT19Q44
a0uZ77UcQE4TPautP3FcAwyJUzVfgrxfUaCmg+UtfH2TsLr6hkmWVtGaE0dpnGO5VomRBw8FyldY
DM0Yo1rBbS4x0JGIf5/goOoHNK0Fegg4FbTBd0IuORrLWYlcAerGjciYVTsteGOKR6/4pn4PQ03n
rU8QeMLAqz7m7aisotZfqedefrze8hTFdMUKCpFPkvRDA2hS9nnNjZ7tjpInnoidujj/Rh/tSncg
rK4BvdcnlQGuS6OLXQO5QVnrDqUnLxwdroF6xgSOit885b0i7isTu1tEDPpknFd9H2Afl2vFNtPv
6ff11ZtqK8CdD+oWDyw6e77KaG0xbhyezTv5ribUmIzzrGGyZNvTfwgjj4OZx6boL9hlVrjrJvq9
0ZvNygd/GyryAdFWNiAEOLrrY0bS1Df5Loxf4IUPrPH2ElRu1CON2z4t0li5r4xOAViSH59/ELru
PUoICtQa4MO4h4/eqksmd6+6bCmwCcQNIV8YVUI8IV4hfXjbK3WhoC4+9sSLvy7il1js8kSyg8Xj
q5RJCa+xDDLFq1L5yvPFwWugBRoeU9mlc596cr0hPPjU8ljdfWciwvPTpXaw0XFn2jXgU3INUD4m
+X8HsIby+ZjH++SaI2ZspXMXTrycyjlyXQveECoTPNRvfzXzUXx/dEIfacNcI7+X4DWTaWv0UvuY
JNetXXfUvTL5zOP7PTXWuSrf7EQT3XKmTwtCEgsJMOe+Khbpl1Nt384PDV7GXnaMKGLGw7tmzC6c
E66BdVZL7+yrO1+vgZB2+Vg1rUu+JRYxBeUTN6XQ5mvgIRFbOaM0u7vIz4uFkVFh8ZNT/KjcBQmz
q1aOIwyVRJ14p8nd1TK3BYOTzHKDaQj+PtHqEHB3MzqWUShJMyvBzxgCr15b3mxatU9a1Y9m56pH
oHQjLn79heTEy2OY3zUfGedwAj0+9c3PcsvxEDblLjqQQD9byMFPusOUOyIJaPu7xKFv62nPa+tr
r3ZyjRIagatN/55ugsWLhbcv6z/wVJJ/q2kfcnV3Y/gMQ1Skg+8FczoVWd3Nt+PHFgefDwoMph1w
6KILXQV3Qwd2PxTuJ9X0mZaawb6WvNacOWUcplUfmFd7F7DemCd9inv85pdCx3xAz3JjSEz8THPO
U6GYKZhYv8Qcxl+iY7AqYJ+JOPpeSpggbMiD2qVuCaIZS1UQPS0SJ6kxfvUHiu8thcMzTnhRUKx8
ReEyFwUThFs5tyLh8QNduf39y7kMAfDdXdJXy1KZr778FAyhvQbCNK4Bctgyb6RvOtWm79NMq3YO
W3mdWQ8m8s+NGlqIXe8GyIvdYkGGnT4IhOFupx3qWUeF/PhwwLKR2+CqfmvdxkZ3lUtYBZii4jSo
b7MuJ+ahCdPURK+hY+xP7rjP3vfuGUWZ8keoMQMR+1ubZPPqkgztwgHxjvIaf+2pZjF+FvFYFwRT
Be4cgc024Sv7/RTD2b8aofH8R++GDiXfKaVy2oBnffOMb/FMhU9p+vKsVgZR6aBwhplPhvpk3q/J
txqg1KGIcuPFtlY1RbbdLpWT4yCNtLgEN9EzWVxMakU7qup7Ysx9hpEZn/SflvCkqknSb88Q0gQM
+rCU/lp3vECyBVWx7BsBsNHUNRC3AJ6o0dJDG1sIi334iuBbaK7gFf2BSYhnoR2M2huYhcWLOIFm
FtfTaFZtbMnjEhh7rwGJwm/l5VL+jnjLQn4mRRlXwQno5ERPjzd/v7RvDnbl9Xbyx01KtXtyLCqj
HSYsqeBNWY+9YYdVhq8TgRhMeyilQcjRKCF605z5Foi5nCQKxCoq4Vin0txlZ3nwEha+8uka2FQt
uCi6OdBSWcCHoPc+qx/mUXI6VA12aUbkcujyh25gCBeE/jtFzBNOtj0KfoUP4Cn6OoT6sjsyMQqr
tYcL+tIqZgX9fdLeyn1laGg4NpeXNEWgpM//T/w7qdY5u73ftALg5wMKBdrFPNhvqRBjPZP6qglS
XFSrAKbKQTCWs9HuWFroqNmJu9o0Q0yzWJOWZs+jqj+ac2m0i0XJsUIhZsvRKHdz8dy3u1xAXhKT
54Sf6W1YRulDVJ4XdWZP1oPTih7yyiEgFiMggPJB67vPplQi//CxFeNsprTUC6zfUjUWWT14oif/
nODExb6ZZvavZHZrr52Zxzc8zfx9chqz9Pdv/WQG4aF1Rx7fWbPVUvvL5a+BzlxGWurXN9f0F7hs
RmPzA6xFpClF0gzUNet98FhVXb1/7dj7d10XcUzfDsGlthRHSL/6BznWC+3odv3hhmZJCfOYyTE1
3n3PF9HqXeNg1kM9eX/nq1TQ/jR3QVblbGMb69E7M9G27qBtAyuDRf7xXtdANnvf4tJbkAUphURm
xABTngKlemjgwT+RkI5nqe/tH+sYysPNRc7f5OjaBqisbUGZsFu86s/z0fpPtiCj2QuJfDE0Bg80
Bvsj92r+dAwpJS4ZtdTD/+oeC1U1z7NLXqzFqz8Dq1eTv3CWXY2euiLSDBvPT54TYe2fgDKW0xsZ
/fNPvGvoNdDzWM+RlN+qEvvTqjqmgLCc8yrdnqalia3vBSG/Gktbopo85CqXknurcHGswXJP2K1q
e+Z+MPU4uXUQX2VWEevKWj64KHGU4DRP9uQS2T9qlNacuRym9qM0w5l753Korwfruv1Y0FhShzKv
sMmALIuOvzdF5zP/0Fz9G4bgiGMD0PZuSfoP197yMdtZlQmvMwYUfDWpMD1vORUO4y5MN0Xbx0iX
fi5yGmcwtMr/xBXNmxwhk/dMvidc2Zx0e1QDgwoYfdSWQdf04wX4J55WxamiHGGfhXMupvhqzGmx
MHvXi0wuZXOXg67OGSJublr3VObIsftjEHqrwtXhxKK+jSeYheEKvcUtIWRvBsssoSfSrdYsn5eb
WvHf3QjVLivcNh8w7Z/fepVPicGZBS7Nv6Tm6a4+Wq0bxxTF46HQO2tOK5koTwa5eCP0s1/p6z+S
5EG89+vumbCKVIpQ5x7hOB/37Wso6ET9gLj3VKNdX8N8D19lz4Z0P3pmmPVWZThvS4riyaEe8q01
hF2zg0HerPC11sLXNAMPoONFF8F5DTI6fVk1/Y8ffSgmNLdblDmvIw+NT/75UGiqQXxPLkVLXC/a
X9XX0Oo51z/ApWrNZ1WpSvbtyhAxKcaAxiG2+UvUYB25fS2n6NSomnd64T2OStoKTQMVgkqB+sDo
N+stagcHhFN9f+pz07K0MUfU4C9BEtp56MH6AbXUBPOqvvqainy9antdhUV9BP89NREJzZTzvARd
GsZ3QnBBwzMsImngRLmXcCYdxwqOLxH7fA0UEnN6+rI3p44+ys7WuypFNV4qhJlWJJv4KyD3FuQE
Gs0IF1wEj0uxXX2bf6bvR1NODzZzw5WqkwLkGu1zBorBLVl6Tb+CkIDSIXd3zatkLVVH46v74L8j
Jjw4uMNTeH99a6njZsv9nOfwwyRaA22EasIu5OtOd126jurS/bZvnh1FqoZjb1rVov31gqOz9Myl
zoPwvoYbDM7rVfHrJr7NTD7c6XyhJdwG+iZN3N+Ue1vvH2l6KNjt1qhMtTX5yTZiORxPVLndTMkl
kt3d74iLDw5fvXjonskn2INi1dYAcyEgXLnmf/RcRkcnFjbgxcRf8MWUfkvL4ofiJ6HZDwvS8drJ
96vvKKW972SLImU7S6T/IT9yDeBdXTr2wTp95Z0KRRHnpnO1bcPQ3Qr30XzqhuqK8+FeRaaSizPg
f5IABU46rOOru0urf+Tnz8s5lJSUUrT3UohiyxcgLGUOtysKTrkQAMEk7kFP9TDlr1CJuBFm6vwf
JAQb4qCuM0rAQ+HVk///AZLc5//5yyaOEP8/H9vEEdc//xfSDenn
.end
.end

.end

